scripts

diff --git a/scripts/esp_upload b/scripts/esp_upload
--- a/scripts/esp_upload
+++ b/scripts/esp_upload
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-SRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
 . $SCRIPT_DIR/utils
 
 TMP_FILE="/tmp/tmp-$(date +%s)-esp-fs.bin"
@@ -12,17 +12,14 @@ IMAGE_SIZE=2072576
 PARTITION_OFFSET="2097152"
 
 ESPTOOL_ARGS=""
-ESP_PYTHON="/Users/kjj/Library/Arduino15/packages/esp8266/tools/python3/3.7.2-post1/python3"
-ESP_UPLOAD_TOOL="/Users/kjj/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/tools/upload.py"
-# ESP_UPLOAD_TOOL="/Users/kjj/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/tools/esptool/esptool.py"
-ESP_MKFS_TOOL="/Users/kjj/Library/Arduino15/packages/esp8266/tools/mklittlefs/3.1.0-gcc10.3-e5f9fec/mklittlefs"
+ESP_PYTHON="$HOME/Library/Arduino15/packages/esp8266/tools/python3/3.7.2-post1/python3"
+ESP_UPLOAD_TOOL="$HOME/Library/Arduino15/packages/esp8266/hardware/esp8266/3.1.2/tools/upload.py"
+ESP_MKFS_TOOL="$HOME/Library/Arduino15/packages/esp8266/tools/mklittlefs/3.1.0-gcc10.3-e5f9fec/mklittlefs"
 
 # Default values
 DATA_DIR="data"
 CHIP_TYPE="auto" # {auto,esp8266,esp32,esp32s2,esp32s3beta2,esp32c3}
-# CHIP_BAUD="115200"
 CHIP_BAUD="921600"
-SERIAL_DEV="/dev/tty.usbserial-"
 SERIAL_PORT=""
 
 # Parse options
@@ -32,57 +29,70 @@ while getopts "d:p:e" opt; do
     p) SERIAL_PORT="$OPTARG" ;;
     e)
         ESP_PYTHON=""
-        ESP_UPLOAD_TOOL="/Users/kjj/Library/Arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool"
-        # ESP_MKFS_TOOL="/Users/kjj/Library/Arduino15/packages/esp32/tools/mkspiffs/0.2.3/mkspiffs"
-        ESP_MKFS_TOOL="/Users/kjj/Library/Arduino15/packages/esp32/tools/mklittlefs/3.0.0-gnu12-dc7f933/mklittlefs"
+        ESP_UPLOAD_TOOL="$HOME/Library/Arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool"
+        ESP_MKFS_TOOL="$HOME/Library/Arduino15/packages/esp32/tools/mklittlefs/3.0.0-gnu12-dc7f933/mklittlefs"
         BLOCK_SIZE="4096"
-        # /Users/kjj/Library/Arduino15/packages/esp32/hardware/esp32/2.0.16/tools/partitions
         CHIP_BAUD="115200"
         IMAGE_SIZE="0x160000"
         ESPTOOL_ARGS="-z"
         PARTITION_OFFSET="0x290000"
-        # ${ESP_UPLOAD_TOOL} --chip auto erase_flash
         ;;
     \?)
-        echo "${RED}Invalid option: -$OPTARG" >&2
-        echo "${WHT}Usage: $0 -d <data_directory> [-p <serial_port>]"
-        return 1
+        report_status "error" "Invalid option: -$OPTARG"
+        echo -e "Usage: $0 -d <data_directory> [-p <serial_port>]"
+        exit 1
         ;;
     esac
 done
 
-echo "${YEL}📦  Packaging Files to Upload${WHT}"
+report_status "info" "📦 Packaging Files to Upload"
 $ESP_MKFS_TOOL \
-    --create $DATA_DIR \
-    --page $PAGE_SIZE \
-    --size $IMAGE_SIZE \
-    --block $BLOCK_SIZE \
-    $TMP_FILE
-echo ""
+    --create "$DATA_DIR" \
+    --page "$PAGE_SIZE" \
+    --size "$IMAGE_SIZE" \
+    --block "$BLOCK_SIZE" \
+    "$TMP_FILE"
+if [ $? -ne 0 ]; then
+    report_status "error" "Failed to package files."
+    exit 1
+fi
 
-# List available serial ports if none provided
-if [ -z $SERIAL_PORT ]; then
-    SERIAL_PORTS=($(ls /dev/tty.* | grep -i usb))
-    # Check if there are available ports
-    if [ ${#SERIAL_PORTS[@]} -eq 0 ]; then
-        echo -e "${RED}🚫 No serial ports found. Please connect a device.${NC}"
-        return 1
-    elif [ ${#SERIAL_PORTS[@]} -eq 1 ]; then
-        SERIAL_PORT="${SERIAL_PORTS}"
+# Auto-select the first matching port if none provided
+if [ -z "$SERIAL_PORT" ]; then
+    SERIAL_PORTS=($(ls /dev/tty.usbserial-* 2>/dev/null))
+    if [ ${#SERIAL_PORTS[@]} -gt 0 ]; then
+        SERIAL_PORT="${SERIAL_PORTS[0]}"
+        report_status "info" "\n${PURP}🛠️  Auto-selected Serial Port:${WHT} $SERIAL_PORT\n"
     else
-        echo -e "${YEL}☑️  Select Serial Port:${PURP}"
-        select port in "${SERIAL_PORTS[@]}"; do
-            SERIAL_PORT="$port"
-            echo -e "${WHT}"
-            break
-        done
+        SERIAL_PORTS=($(ls /dev/tty.* | grep -i usb))
+        if [ ${#SERIAL_PORTS[@]} -eq 0 ]; then
+            report_status "error" "No serial ports found. Please connect a device."
+            exit 1
+        elif [ ${#SERIAL_PORTS[@]} -eq 1 ]; then
+            SERIAL_PORT="${SERIAL_PORTS[0]}"
+            # report_status "success" "Using Serial Port: $SERIAL_PORT"
+        else
+            report_status "info" "🛠️  Select Serial Port:"
+            select port in "${SERIAL_PORTS[@]}"; do
+                SERIAL_PORT="$port"
+                break
+            done
+        fi
     fi
 fi
-echo -e "${YEL}🛜  Uploading Packaged Files${WHT}"
-$ESP_PYTHON $ESP_UPLOAD_TOOL \
+
+report_status "info" "${BLU}🛜  Uploading Packaged Files"
+$ESP_PYTHON "$ESP_UPLOAD_TOOL" \
     --before default_reset \
     --after hard_reset \
-    --chip $CHIP_TYPE \
-    --port $SERIAL_PORT \
-    --baud $CHIP_BAUD \
-    write_flash $ESPTOOL_ARGS $PARTITION_OFFSET $TMP_FILE
+    --chip "$CHIP_TYPE" \
+    --port "$SERIAL_PORT" \
+    --baud "$CHIP_BAUD" \
+    write_flash $ESPTOOL_ARGS "$PARTITION_OFFSET" "$TMP_FILE"
+
+if [ $? -ne 0 ]; then
+    report_status "error" "Upload Failed"
+    exit 1
+fi
+
+report_status "success" "🎉 Done!"
